site_name: Careers
site_url: https://careers.hintjen.com
site_description: Hintjen is a global leader in the development of innovative software solutions.
theme:
  name: material
  logo: images/H.png
  favicon: images/hintjen.png
extra_css:
  - stylesheets/extra.css
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg